[arch]
image=docker.io/library/archlinux:latest
#image=ghcr.io/ublue-os/arch-toolbox:latest
additional_packages="eza fish git github-cli helix micro wezterm yazi zellij"
additional_packages="base-devel clang gdb lldb rust-analyzer rustup"
additional_packages="chezmoi fastfetch hyfetch inter-font starship"
exported_apps="WezTerm"
home="${HOME}/.local/share/arch-toolbox"
#init_hooks=[ -f /etc/init ] || sudo -u $USER -- paru -S --needed --noconfirm rate-mirrors maplemono-ttf
init=false
nvidia=false
pull=true
root=false
replace=true
